### ISSUE TITLE
Message gap detected?

### ISSUE THREAD

**Issue by Sushisource** [mrmekon/ossuary#3]
Hey, thanks a lot for publishing this crate! Really cool simple plug-n-play way to encrypt stuff. I've got pretty close to having success with it in my app, but still struggling a bit through the handshake. Namely I keep running into "Message gap detected" errors on the server side, and I just have no idea why.

My code is located here: https://github.com/Sushisource/hubtain/tree/ossuary

The specific function that does the handshaking: https://github.com/Sushisource/hubtain/blob/ossuary/src/ossuary_stream.rs#L27

You can run `cargo test encrypt -- --nocapture` to repro the problem (on nightly). There's a lot of debug output.

In general though, the client seems to finish handshaking just fine, while the server whines with this error on the last packet it receives. I'm not transmitting any other data over the stream besides the handshake data (it crashes before that point).

I understand if you don't have time to go digging through my code :laughing:, but any pointers are appreciated. Thanks!

**Comment by mrmekon** [comment]
Hey @Sushisource, thanks for trying out ossuary!  You do raise a good point... it gives you no facilities for debugging.

I had a look at your code, and it looks like the issue is that you are giving the entire `rb` buffer to `recv_handshake`, even though it is only partially filled with the next packet.  For the first packet you receive from the client, you write both the entire first packet and a large chunk of zeroes.  Ossuary buffers those zeroes, and on the next call it tries to parse them as the next packet.

Changing:
```let mut rb = Cursor::new(rb);```
to
```let mut rb = Cursor::new(&rb[0..bytes_read_from_stream]);```
seems to be enough to get through the handshake.  Then the tests fail elsewhere :)

Feel free to ask if you run into anything else.  I'm very interested in feedback.
